CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT,name VARCHAR, description TEXT);
CREATE TABLE IF NOT EXISTS shop_lists (id INTEGER PRIMARY KEY AUTOINCREMENT,name VARCHAR ,state INTEGER);
CREATE TABLE IF NOT EXISTS shops (id INTEGER PRIMARY KEY AUTOINCREMENT,name VARCHAR,localisation VARCHAR,website VARCHAR,phoneNumber INTEGER,openingHours TEXT);
CREATE TABLE IF NOT EXISTS shop_list_products (id INTEGER PRIMARY KEY AUTOINCREMENT,quantity INTEGER ,order INTEGER NULL DEFAULT NULL,product_id INTEGER ,shop_list_id INTEGER ,shop_id INTEGER);
